name: Gitleaks Scan

on: 
  pull_request

permissions:
  contents: read
  pull-requests: read

jobs:
  gitleaks:
    name: Run Gitleaks
    runs-on: cloudwalk-k8s-runner
    if: ${{ github.repository != 'cloudwalk/actions' }}

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GHA_PAT }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE_PUBLIC }}
          GITLEAKS_ENABLE_UPLOAD_ARTIFACT: "false"
          GITLEAKS_VERSION: 8.26.0